networks:
  flask-net:
    driver: bridge

volumes:
  app-data:
  postgres-data:

services:
  app:
    image: "REDACTED:5050/team-18/backend:latest"
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://REDACTED/ping"]
      interval: 10s
      retries: 30
      timeout: 3s
      start_period: 10s
    restart: "no"
    ports:
      - "REDACTED:8080"
    env_file:
      - .env
    environment:
      - SERVER_ADDRESS=REDACTED
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      - APP_DEBUG=${APP_DEBUG}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app-data:/usr/src/app
    networks:
      - flask-net

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flask-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]
